@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-down-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-down-> "1" UniqueJobList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -down-> Person
UniqueJobList -down-> Job

Person -up-> "*" Tag

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address

Job *-down-> JobTitle
Job *-down-> JobRounds
Job *-down-> JobSkills
Job *-down-> JobType
@enduml
